[project]
name = "belbin"
version = "0.1.1"
description = "The Belbin Team-Role Self-Perception Inventory (Chinese)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "polars>=1.22.0",
    "rsconnect-python>=1.25.1",
    "shiny>=1.2.1",
]
